env:
  es6: true
extends:
  - google
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier/@typescript-eslint'
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  project: './tsconfig.json'
  sourceType: module
plugins:
  - react
  - babel
  - '@typescript-eslint'
rules:
  require-jsdoc:
    - off
  quotes:
    - warn
    - single
  no-invalid-this:
    - off
  babel/no-invalid-this:
    - error
  '@typescript-eslint/no-empty-function':
    - off
  '@typescript-eslint/ban-types':
    - off
  prettier/prettier:
    - warn
